#!/usr/bin/fish
chmod 755 NHDL

if test (id -u) = 0
    #the install script is run as root, install it in /usr/bin/
    install NHDL "/usr/bin/"
else
    #the install script is run by a normal user, install under local bin dir
    if test -d "$HOME/.local/bin"
        install NHDL "$HOME/.local/bin/"
    else
        mkdir -p "$HOME/.local/bin"
        install NHDL "$HOME/.local/bin/"
    end    
    
    if test -f "/usr/bin/NHDL"; or test -f "$HOME/.local/bin/NHDL"
        printf "%s\n" "program installed correctly."
    else
        printf "%s\n" "error while installing NHDL; aborting." > "/dev/stderr"
    end
    
    if test -z (echo $PATH | grep ".local/bin/")
        set $choice ""
        printf "%s\n" \
            ".local/bin/ (the default installation directory) is not in PATH, do you want to add it now? [Y/n]"
        read -P ">" choice
        printf "\n"
        switch "$choice"
            case "Y" "ye" "yes" 
                printf "set PATH $HOME/.local/bin \$PATH" >> "$HOME/.config/fish/config.fish"
            case "n" "no"
                printf "%s\n" \
                "in order to use NHDL, please add $HOME/.local/bin/ to PATH in your shell's configuration file."
            case "*"
                printf "%s\n" "invalid option." \
                              "aborting."
        end
    end
end

